import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export function exportInvoicePDF(inv) {
  const doc = new jsPDF();
  const emerald = [5, 150, 105];
  const teal = [20, 184, 166];

  // Header gradient bar
  doc.setFillColor(...emerald);
  doc.rect(0, 0, 210, 18, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Clinio', 14, 12);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text('Clinic Care, Organized', 14, 16.5);

  // Invoice number + status
  doc.setTextColor(...emerald);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(`INVOICE`, 140, 32);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(80, 80, 80);
  doc.text(inv.invoiceNumber, 140, 40);

  // Patient info
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Billed To', 14, 32);
  doc.setFont('helvetica', 'normal');
  doc.text(`${inv.patient?.firstName || ''} ${inv.patient?.lastName || ''}`, 14, 39);

  // Dates
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(9);
  const issued = inv.createdAt ? new Date(inv.createdAt).toLocaleDateString() : '—';
  const due = inv.dueDate ? new Date(inv.dueDate).toLocaleDateString() : '—';
  doc.text(`Issued: ${issued}`, 140, 48);
  doc.text(`Due: ${due}`, 140, 54);

  // Line items table
  const rows = (Array.isArray(inv.lineItems) ? inv.lineItems : []).map(li => [
    li.description || '—',
    li.quantity ?? 1,
    `$${Number(li.unitPrice || 0).toFixed(2)}`,
    `$${(Number(li.quantity || 1) * Number(li.unitPrice || 0)).toFixed(2)}`,
  ]);

  autoTable(doc, {
    startY: 65,
    head: [['Description', 'Qty', 'Unit Price', 'Amount']],
    body: rows.length ? rows : [['—', '—', '—', '—']],
    headStyles: { fillColor: emerald, textColor: 255, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [240, 253, 250] },
    columnStyles: { 0: { cellWidth: 90 }, 1: { halign: 'center', cellWidth: 20 }, 2: { halign: 'right', cellWidth: 35 }, 3: { halign: 'right', cellWidth: 35 } },
    margin: { left: 14, right: 14 },
  });

  const finalY = doc.lastAutoTable.finalY + 8;
  doc.setFontSize(10);
  doc.setTextColor(80, 80, 80);
  doc.text('Subtotal:', 140, finalY);
  doc.text(`$${Number(inv.subtotal || 0).toFixed(2)}`, 196, finalY, { align: 'right' });
  if (inv.tax) {
    doc.text('Tax:', 140, finalY + 7);
    doc.text(`$${Number(inv.tax).toFixed(2)}`, 196, finalY + 7, { align: 'right' });
  }
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(...emerald);
  doc.text('Total:', 140, finalY + 16);
  doc.text(`$${Number(inv.total || 0).toFixed(2)}`, 196, finalY + 16, { align: 'right' });

  // Status badge
  const statusColor = inv.status === 'paid' ? teal : inv.status === 'overdue' ? [234, 88, 12] : emerald;
  doc.setFillColor(...statusColor);
  doc.roundedRect(14, finalY + 10, 28, 9, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text((inv.status || 'draft').toUpperCase(), 28, finalY + 16.5, { align: 'center' });

  // Footer
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Clinio — clinio-health.vercel.app', 105, 285, { align: 'center' });

  doc.save(`${inv.invoiceNumber}.pdf`);
}
